app/models/file.py
from ..extensions import db

app/models/user.py
from datetime import datetime, timezone
from ..extensions import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    timestamp = db.Column(db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    

app/__init__.py
from flask import Flask
from .extensions import db, migrate
from .routes.index import main_bp
from .routes.auth import auth_bp
import os

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='docify',
        SQLALCHEMY_DATABASE_URI="sqlite:///" + os.path.join(app.instance_path, 'db.sqlite3'),
        SQLALCHEMY_TRACK_MODIFICATIONS = False
    )
    try:
        os.makedirs(app.instance_path)
        storage = os.path.join(app.instance_path, "storage", "users")
        os.makedirs(storage, exist_ok = True)
    except OSError:
        pass
    
    db.init_app(app)
    migrate.init_app(app, db)
    from .models import user, file
    
    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp)

    return app

app/routes/auth.py
from flask import Blueprint, render_template

auth_bp = Blueprint("auth",__name__, url_prefix="/auth")


@auth_bp.route("/register")
def register():
    return render_template("auth/register.html")

@auth_bp.route("/login")
def login():
    return render_template("auth/login.html")

app/routes/index.py
from flask import Blueprint, render_template

main_bp = Blueprint("main",__name__)

@main_bp.route("/")
def home():
    return render_template("index.html")

app/templates/index.html
{% extends 'layout.html' %}
{% block body %}
    <header>
        <h1>Docify</h1>
    </header>
    <main>
        <div>
            <strong>Write once. Export everywhere.</strong>
            <p>Docify helps you write and manage text effortlessly.</p>
            <p>Use special syntax to structure your 
                content, keep everything organized, and download your files in formats like 
                <strong>PDF, TXT, Word, and more</strong>.
            </p>
            <p>
                Whether you're writing notes,
                documentation, or structured content,
                Docify makes document creation simple, fast, and flexible.
            </p>
            <strong>Start writing with Docify.</strong>
            <a href="{{ url_for('auth.register')}}">Register now</a>
            <p>already registered?</p>
            <a href="{{ url_for('auth.login')}}">Login</a>
        </div>
    </main>
    <footer>

    </footer>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Docify</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>